### ISSUE TITLE
The pretrain model has wrong state_dict keys

### ISSUE THREAD

**Issue by cia1099** [hzykent/VMNet#1]
Hi, I get some issue about
1. I test the the script with [pretrain model](https://drive.google.com/drive/folders/1j5_uTL4xrsVZ5svPOp3LENcgvsJehDbx)
```
python run.py --test --exp_name test_split --data_path path/to/processed_data
```
The output logs are:
```
use_cuda: True
exp_name: test_split
#parameters 17463870
Traceback (most recent call last):
  File "run.py", line 279, in <module>
    test(exp_name, test_files)
  File "run.py", line 139, in test
    model.load_state_dict(checkpoint['model_state_dict'])
  File "/home/keroro/Program_Files/miniconda3/envs/tt/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for VMNet:
	Unexpected key(s) in state_dict: "Geo_branch.mid_geo.geo_0.lin_edge.weight", "Geo_branch.mid_geo.geo_0.lin_edge.bias", "Geo_branch.mid_geo.geo_1.lin_edge.weight", "Geo_branch.mid_geo.geo_1.lin_edge.bias", "Geo_branch.cd_5.geo_0.lin_edge.weight", "Geo_branch.cd_5.geo_0.lin_edge.bias", "Geo_branch.de5_geo.geo_0.lin_edge.weight", "Geo_branch.de5_geo.geo_0.lin_edge.bias", "Geo_branch.de5_geo.geo_1.lin_edge.weight", "Geo_branch.de5_geo.geo_1.lin_edge.bias", "Geo_branch.cd_4.geo_0.lin_edge.weight", "Geo_branch.cd_4.geo_0.lin_edge.bias", "Geo_branch.de4_geo.geo_0.lin_edge.weight", "Geo_branch.de4_geo.geo_0.lin_edge.bias", "Geo_branch.de4_geo.geo_1.lin_edge.weight", "Geo_branch.de4_geo.geo_1.lin_edge.bias", "Geo_branch.cd_3.geo_0.lin_edge.weight", "Geo_branch.cd_3.geo_0.lin_edge.bias", "Geo_branch.de3_geo.geo_0.lin_edge.weight", "Geo_branch.de3_geo.geo_0.lin_edge.bias", "Geo_branch.de3_geo.geo_1.lin_edge.weight", "Geo_branch.de3_geo.geo_1.lin_edge.bias", "Geo_branch.cd_2.geo_0.lin_edge.weight", "Geo_branch.cd_2.geo_0.lin_edge.bias", "Geo_branch.de2_geo.geo_0.lin_edge.weight", "Geo_branch.de2_geo.geo_0.lin_edge.bias", "Geo_branch.de2_geo.geo_1.lin_edge.weight", "Geo_branch.de2_geo.geo_1.lin_edge.bias", "Geo_branch.cd_1.geo_0.lin_edge.weight", "Geo_branch.cd_1.geo_0.lin_edge.bias", "Geo_branch.de1_geo.geo_0.lin_edge.weight", "Geo_branch.de1_geo.geo_0.lin_edge.bias", "Geo_branch.de1_geo.geo_1.lin_edge.weight", "Geo_branch.de1_geo.geo_1.lin_edge.bias", "Geo_branch.cd_0.geo_0.lin_edge.weight", "Geo_branch.cd_0.geo_0.lin_edge.bias", "Geo_branch.de0_geo.geo_0.lin_edge.weight", "Geo_branch.de0_geo.geo_0.lin_edge.bias", "Geo_branch.de0_geo.geo_1.lin_edge.weight", "Geo_branch.de0_geo.geo_1.lin_edge.bias".
```

What are the `Unexpected key(s)` in state_dict ? does the VMNet not defined?

2. When I preprocess the data, I had build [VCGlib](https://github.com/cnr-isti-vclab/vcglib)
`vcglib/apps/tridecimator` and  `vcglib/apps/sample/trimesh_clustering` , I add environment path by:
```
export PATH=$PATH:/path/to/vcglib/apps/tridecimator:/path/to/vcglib/apps/sample/trimesh_clustering
# create links
sudo ln -s /path/to/vcglib/apps/tridecimator/tridecimator /usr/local/bin
sudo ln -s /path/to/vcglib/apps/sample/trimesh_clustering/trimesh_clustering /usr/local/bin
```
But run the preprocess, there is core dumped:
```considered_rooms_path:dataset/data_split/scannetv2_train.txt
in_path:../scannet/VMtest
out_path:../scannet/VMNet_data/train/
[0.02, 0.04, 30, 30, 30, 30, 30]
Processing ../scannet/VMtest/scene0000_00/scene0000_00_vh_clean_2.ply
curr_dir: ../scannet/VMNet_data/train/scene0000_00
trimesh_clustering: ../../../vcg/simplex/vertex/component.h:75: vcg::vertex::EmptyCore<TT>::ColorType& vcg::vertex::EmptyCore<TT>::C() [with TT = MyUsedTypes; vcg::vertex::EmptyCore<TT>::ColorType = vcg::Color4<unsigned char>]: Assertion `0' failed.
Aborted (core dumped)
trimesh_clustering: ../../../vcg/simplex/vertex/component.h:75: vcg::vertex::EmptyCore<TT>::ColorType& vcg::vertex::EmptyCore<TT>::C() [with TT = MyUsedTypes; vcg::vertex::EmptyCore<TT>::ColorType = vcg::Color4<unsigned char>]: Assertion `0' failed.
Aborted (core dumped)
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/keroro/Program_Files/miniconda3/envs/tt/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/keroro/Program_Files/miniconda3/envs/tt/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "prepare_data.py", line 226, in process_frame
    old_vertices=vertices[-1])
  File "prepare_data.py", line 173, in quadric_error_metric
    '.ply', '.csv'), old_vertices=old_vertices, new_vertices=vertices_l)
  File "prepare_data.py", line 78, in csv2npy
    with open(in_file_path, 'r') as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: '../scannet/VMNet_data/train/scene0000_00/curr_mesh.csv'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "prepare_data.py", line 295, in <module>
    pf_pool.map(process_frame_p, file_paths)
  File "/home/keroro/Program_Files/miniconda3/envs/tt/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/keroro/Program_Files/miniconda3/envs/tt/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: '../scannet/VMNet_data/train/scene0000_00/curr_mesh.csv'

```
Where should I set the correct environment path for `vcglib/apps/tridecimator` and  `vcglib/apps/sample/trimesh_clustering`?

**Comment by hzykent** [comment]
Thank you for your comment.

I checked the code and find that the issue is related to the torch_geometric package. 

It turns out that they changed some lines in the newest version. Specifically, from:
                        
> self.lin_edge = Linear(1, 1)

to:

>  self.lin_edge = self.register_parameter('lin_edge', None) 

This should not have a large impact, but I'm afraid that you need to install torch_geometric 1.6.3 to load the pre-trained model correctly.

**Comment by hzykent** [comment]
For environment path, I add these lines to the .bashrc file in my system:

> export PATH=/path/to/tridecimator/:$PATH

> export PATH=/path/to/trimesh_clustering/:$PATH

**Comment by cia1099** [comment]
@hzykent Thamks for your patient and response to me
Yeah, I can read the keys correctly since I replace version of torch_geometry to 1.6.3 now

For `trimesh_clustering` error, I found the same issue in [#36](https://github.com/cnr-isti-vclab/vcglib/issues/36)
There is the solution in `trimesh_clustering.cpp` for the vertex by replace
>class MyVertex  : public vcg::Vertex< MyUsedTypes, vcg::vertex::Coord3f, vcg::vertex::Normal3f, vcg::vertex::BitFlags  >{};

with
>class MyVertex  : public vcg::Vertex< MyUsedTypes, vcg::vertex::Coord3f, vcg::vertex::Normal3f, vcg::vertex::BitFlags, vcg::vertex::Color4b >{};

---

Every thing seems right, but the `prepare_data.py` still run error in the line 78:
```python
with open(in_file_path, 'r') as csvfile:
```
I got
>FileNotFoundError: [Errno 2] No such file or directory: '/home/keroro/project/scannet/VMNet_data/train/scene0000_00/curr_mesh.csv'

I don't understand where the `.csv` comes up? In the script there is not write any csv files, Why read the csv file? What csv2npy function do. The nested function is `process_frame`-->`if level >=1` --> `quadric_error_metric` --> `csv2npy`, process doesn't write any `csv` file.

**Comment by hzykent** [comment]
Hi,
The csv file is generated by tridecimator. After running line 155:

> os.system(f"tridecimator " f"{curr_file_path} {curr_file_path} {ratio} -On -C > /dev/null")

There will be two files in the folder:

> curr_mesh.csv  curr_mesh.ply

I guess the tridecimator in your system may not be compiled correctly.

**Comment by cia1099** [comment]
Oops
>os.system(f"tridecimator " f"{curr_file_path} {curr_file_path} {ratio} -On -C > /dev/null")

I think the second argument should be {curr_file_path[:-3]+'csv'} instead of {curr_file_path}, because it means output file
The modified line is
 > os.system(f"tridecimator " f"{curr_file_path} {curr_file_path[:-3]+'csv'} {ratio} -On -C > /dev/null")

Does it correct in originally logic for running `tridecimator`?

**Comment by hzykent** [comment]
This line of code is adpoted from DCM-Net, and I think it is written in the correct way. 

For example, in a directory with file current_mesh.ply, run ll, the output is:

> -rw-r--r-- 1 root root 800772 Aug 11 16:06 curr_mesh.ply

If you run this line:

> tridecimator curr_mesh.ply curr_mesh.ply 30 -On -C > /dev/null

The output would be:

> -rw-r--r-- 1 root root 768671 Aug 11 17:01 curr_mesh.csv
-rw-r--r-- 1 root root 238990 Aug 11 17:01 curr_mesh.ply

The mesh is downsampled correctly and the other information is stored in csv file.

But if this line is run:

> tridecimator curr_mesh.ply curr_mesh.csv 30 -On -C > /dev/null

The output would be:

> -rw-r--r-- 1 root root 768671 Aug 11 17:00 curr_mesh.csv
-rw-r--r-- 1 root root 800772 Aug 11 16:06 curr_mesh.ply

The csv file is correctly stored but the downsampled mesh is not.

**Comment by cia1099** [comment]
I think you are right, the output should be downsample mesh.
I checked source code [tridecimator.cpp](https://github.com/cnr-isti-vclab/vcglib/blob/master/apps/tridecimator/tridecimator.cpp) and [export_ply.h](https://github.com/cnr-isti-vclab/vcglib/blob/master/wrap/io_trimesh/export_ply.h)
There are not exporting any `csv` files, what source code of `tridecimator` you belong, does you rewrite some else?

**Comment by hzykent** [comment]
I didn't rewrite any code regarding tridecimator. I just downloaded the code from vcglib github repository and basically followed the preprocessing steps of DCM-Net.

**Comment by cia1099** [comment]
Hi,
Can you show me the message of after executing `tridecimator curr_mesh.ply curr_mesh.ply 30 -On -C` ? `eliminated "> /dev/null"`
I actually get the downsample mesh following the step:
> $ll
total 2320
drwxrwxr-x  2 keroro keroro    4096  8  13 11:18 ./
drwxrwxr-x 45 keroro keroro    4096  8  11 11:12 ../
-rw-rw-r--  1 keroro keroro 2367239  8  13 11:18 curr_mesh.ply
$tridecimator curr_mesh.ply curr_mesh.ply 30 -On -C
mesh loaded 64445 122592 
NOT Using OptimalPlacement
Cleaning mesh before simplification
Removed 0 duplicate and 50 unreferenced vertices from mesh 
reducing it to 30
Initial Heap Size 735552
mesh  299 29 Error 1.46578 eap sz    348763 err 9.75846e-08 
\
Completed in (0.202+0.981) sec
$ll
total 16
drwxrwxr-x  2 keroro keroro 4096  8  13 11:18 ./
drwxrwxr-x 45 keroro keroro 4096  8  11 11:12 ../
-rw-rw-r--  1 keroro keroro 4162  8  13 11:19 curr_mesh.ply

As you can see, the `tridecimator` executes as normal, the size of curr_mesh.ply down to 4162 from 2367239, but I still not create any `csv` file
Excuse, can you provide your executable `tridecimator*` for me? Let me run and check the binary file that not compiled incorrectly
I would appreciate very much

**Comment by timothyliu0912** [comment]
I have the same problem too

**Comment by hzykent** [comment]
![image](https://user-images.githubusercontent.com/43575254/129381260-982beaa6-6d9a-4941-9636-5485f52f808a.png)
Hi, unfortunately, I did not get any messages when executing tridecimator. 
The executable file of tridecimator could be downloaded through this link https://drive.google.com/file/d/16is5cUULPhdTgRyG1fNbFMxbvWUB_V2Y/view?usp=sharing. (not sure if it is runnable in your system).
P.S. Maybe you can ask the authors of DCM-Net for help since these preprocessing steps are adpoted from DCM-Net.

**Comment by hzykent** [comment]
Oh, I notice that I'm actually using the vcglib fork created by the author of DCM-Net instead of the official repository. I guess it may be the point causing all these problems.
I updated the link of vcglib. If it solved the problems, I'm sorry for the troublesome.

**Comment by cia1099** [comment]
@hzykent, Thanks this can be work now
