### ISSUE TITLE
about downloading ScanNet

### ISSUE THREAD

**Issue by cjyiiiing** [hzykent/VMNet#2]
Hi,
I haven't used ScanNet before, so I'm not familiar with it and need your help. Due to my limited memory space, I want to only download the needed parts of the ScanNet. Since you say:
> Our method relies on the .ply as well as the .labels.ply files. 

so does it mean that I can download the ScanNet only using this two command?
``` 
download-scannet.py -o [directory in which to download] --type _vh_clean_2.ply
download-scannet.py -o [directory in which to download] --type _vh_clean_2.labels.ply
```
In addition, how much memory space is needed to store the processed data?

**Comment by hzykent** [comment]
Hi, thank you for your interest.

Yes, you can download the needed files using those two commands. The processed data is about 55Gb.

**Comment by cjyiiiing** [comment]
Wow!! Thanks for your very quick reply. It really helps me!
