### ISSUE TITLE
about Matterport3D results

### ISSUE THREAD

**Issue by lcysonya** [hzykent/VMNet#3]
Hi~

Thanks for the great work. I find your work use Matterport3D datatset  and get pretty good results showed in the paper.  

But I don’t find any code related to Matterport3D in this repository. I wonder if you can share the Matterport3D related code and give a brief description of how to reproduce the results on Matterport3D. 

Looking forward to your reply and this will help a lot.

**Comment by hzykent** [comment]
Hi,

I appreciate your interest. 

Unfortunately, the original code for Matterport3D is lost. However, the data structures of ScanNet and Matterport3D are pretty similar with only one major difference (Matterport3D has 21 classes while ScanNet has 20). Using the current codebase, you can adapt it to Matterport3D by simply editing the label matching part of the data pipeline and changing the output channel number of the network from 20 to 21.

Hope this can help.

Cheers~
