### ISSUE TITLE
Quadric Error Metrics: contraction of non-connected vertices possible?

### ISSUE THREAD

**Issue by BenjaminEpple** [hzykent/VMNet#4]
Hi there,

Thanks for your amazing work! 

I would be glad if you could please answer the following question about the usage of QEM in VMNet.  
The publication seems to indicate that for _vertex contraction_ only vertices _connected by edges_ are considered. However, in the original [QEM publication](http://www.cs.cmu.edu/~garland/Papers/quadrics.pdf), the authors also propose selecting vertex pairs for contraction based on their Euclidean distance. They use a threshold value ``t`` for the Euclidean distance.

Using only vertices connected by edges would imply a threshold of ``t = 0``. In [prepare_data.py](https://github.com/hzykent/VMNet/blob/main/prepare_data.py), Tridecimator from VCGlib is called. If I understand the call correctly, the optional argument ``-e`` is not passed which specifies the threshold. In the Tridecimator application, the threshold ``t`` then defaults to ``inf``, meaning all pairs of vertices would be eligible for contraction. 

Therefore I would like to know: Is contraction of non-connected vertices possible in VMNet? 

Thanks a lot for your time, Benjamin

**Comment by hzykent** [comment]
Hi,

Thank you for your interest.

I think the contraction of non-connected vertices is possible in VMNet. However, according to the visualization of the output meshes of VC and QEM methods, this seems not to be a serious issue and the QEM method produces simplified meshes with much better-reserved topology than the VC method.

Cheers, Zeyu
