### ISSUE TITLE
Issue of 'input voxels are not valid'

### ISSUE THREAD

**Issue by Hao-HUST** [hzykent/VMNet#5]
Hi, authors, thanks for sharing your work.

When I tried to train VMNet with my own training data, the valid_idxs is not meet the assert condition, like
https://github.com/hzykent/VMNet/blob/61816831ca006862c3b0e6fcaa83e74e690dba0a/dataset/scannetv2.py#L158

I think the problem is related to my own data, but the specific reason for such an issue is unclear. Do you have any suggestions about that?

PS: I use the prepare_data.py script to preprocess my own data, as same as the preprocessing procedure for the ScanNet dataset.

**Comment by hzykent** [comment]
Hi, Thank you for your interest.

Some points of your scene seem out of the full_scale (set to [4096, 4096, 4096]). This may result from a scene that is too large or a voxel_size set too small. 

FYI, the related operations written in the dataset file just move the scene around randomly within the full_scale.

Cheers~

**Comment by Hao-HUST** [comment]
Hi, thanks for your respondence.

I modified the scale parameter for scannetv2 from the default(50) to 5 and maintain the default full_scale (set to [4096, 4096, 4096]), the training processing works well. I noticed that the scale parameter is used for affine linear transformation, is that a kind of data augment? And do you have any suggestions for setting the scale parameter for custom datasets?

**Comment by hzykent** [comment]
The scale parameter is used for voxelization. It set the voxel size to 1 / scale meter. (e.g. scale = 50 equals voxel size = 0.02m) And the full_scale is the space set for random placement of the input scene. For the default scale (50), the full_scale is a space of size [81.92m, 81.92m, 81.92m]. For the scannet dataset, the default space is large enough. If your scene is out of this range, you could simply enlarge the voxel size or enlarge the full_scale otherwise.

**Comment by Hao-HUST** [comment]
Hi, thanks for your advice. 

One more question, the voxel size or voxel resolution is related to the effectiveness of the Sparse CNN for Point Cloud, so if I want to keep the performance(just like you did in ScanNet), I should modify the full_scale but maintain the scale, right?

**Comment by hzykent** [comment]
I think so.

**Comment by Hao-HUST** [comment]
Great, thanks a lot!
